name: fullstack-prod

networks:
  fullstack-prod:
    driver: bridge
    enable_ipv6: false

services:
  envoy:
    image: bitnami/envoy:latest
    networks:
      - fullstack-prod
    volumes:
      - ./envoy.prod.yaml:/opt/bitnami/envoy/conf/envoy.yaml

  nginx:
    image: nginx:alpine
    networks:
      - fullstack-prod
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"

  backend:
    build:
      context: ../
      dockerfile: apps/backend/Dockerfile
    networks:
      - fullstack-prod

  frontend:
    build:
      context: ../
      dockerfile: apps/frontend/Dockerfile
    networks:
      - fullstack-prod
