name: fullstack-dev

networks:
  fullstack-dev:
    driver: bridge
    enable_ipv6: false

services:
  envoy:
    image: bitnami/envoy:latest
    networks:
      - fullstack-dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./envoy.dev.yaml:/opt/bitnami/envoy/conf/envoy.yaml
    ports:
      - "9099:9099"
      - "9100:9100"

  nginx:
    image: nginx:alpine
    networks:
      - fullstack-dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"

